#!/bin/bash

# Copyright 2014--2015 Jan Pazdziora
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

#inherit init (PID=1) variables

for e in $(tr "\000" "\n" < /proc/1/environ); do
        eval "export $e"
done

function usage () {
	if [ -n "$1" ] ; then
		echo $1 >&2
	else
		echo "Start as docker run -e PASSWORD=\$THE_ADMIN_PASSWORD image" >&2
		echo "    with -h <the-FQDN-hostname> and possibly --link <FreeIPA-container>:ipa" >&2
	fi
	exit 1
}

function stop_running () {
        echo "trying to stop"
	systemctl stop sssd

	# here we need to get the PID of the java process and send a sigterm also to it
}
trap stop_running SIGTERM

rm -rf /var/run/*.pid


if [ -n "$IPA_PORT_53_UDP_ADDR" ] ; then
	echo "nameserver $IPA_PORT_53_UDP_ADDR" > /etc/resolv.conf
fi

if [ -f /etc/ipa/ca.crt ] ; then
	HOSTNAME_IPA=$(cat /etc/hostname.ipa-client)
	if [ ! "$HOSTNAME_IPA" == "$(hostname -f)" ] ; then
                echo "The container hostname is $(hostname -f) and is different from $HOSTNAME_IPA; this container is already registered with a different hostname use the correct -h value option." >&2
		if hostname $HOSTNAME_IPA ; then
			echo "Hostname set to $HOSTNAME_IPA"
		else
			echo "The container hostname is $(hostname -f) and cannot set $HOSTNAME_IPA; run with -h." >&2
			exit 1
		fi
	fi
	echo "System is already FreeIPA-enrolled, starting the services."
	echo "System is ready."
    cd /usr/hdp/2.6.0.3-8/zeppelin
    bin/zeppelin.sh
else

	IPA=$( curl -si http://$IPA_PORT_80_TCP_ADDR/ | perl -lne 'm!^Location:\shttps?://(.+?)/! and print $1' )
	IPASERVERDOMAIN=${IPA#*.}
	HOSTNAME_FQDN=$( hostname ).$IPASERVERDOMAIN
	HOSTNAME_OPTS=--hostname=$HOSTNAME_FQDN
	
	# Replace last
	rancher_host_entry=$(tail -n 1 /etc/hosts | head -n1 | awk '{print $2;}')
	head -n -1 /etc/hosts > /etc/hosts.tmp
	echo "$(hostname -I) $(hostname).$IPASERVERDOMAIN $(hostname) $rancher_host_entry" >> /etc/hosts.tmp	
	cat /etc/hosts.tmp /etc/hosts
	echo "/etc/hosts updated..."

	/usr/sbin/ipa-client-install $IPA_CLIENT_INSTALL_OPTS --force --no-nisdomain -p admin -w "$PASSWORD" -U -v  --mkhomedir --realm=$REALM --domain=$IPASERVERDOMAIN --server=$IPASERVER  --enable-dns-updates < /dev/null
	cp -f /etc/hostname /etc/hostname.ipa-client
	echo "FreeIPA-enrolled."
	
	sed -i "/^\[sssd\].*/s//enumerate = True\\n\[sssd\]/" /etc/sssd/sssd.conf
	more /etc/sssd/sssd.conf
	echo "Restarting SSSD"
	/usr/bin/systemctl restart sssd
	echo "Aligning the users"
	sleep 50
	getent passwd
	echo "kiniting admin"
	echo -n "$PASSWORD" | kinit admin

	cp /usr/hdp/2.6.0.3-8/zeppelin/conf/shiro.ini.template /usr/hdp/2.6.0.3-8/zeppelin/conf/shiro.ini
	sed -i "/^#ldapRealm =.*/s//ldapRealm = org.apache.zeppelin.realm.LdapGroupRealm/" /usr/hdp/2.6.0.3-8/zeppelin/conf/shiro.ini
	sed -i "/^#ldapRealm.contextFactory.url.*/s//ldapRealm.contextFactory.url = ldap:\/\/tst-kerb1.pochdp.csi.it:389/" /usr/hdp/2.6.0.3-8/zeppelin/conf/shiro.ini
	sed -i "/^#ldapRealm.contextFactory.environment\[ldap.searchBase\].*/s//ldapRealm.contextFactory.environment\[ldap.searchBase\] = DC=pochdp,DC=csi,DC=it/" /usr/hdp/2.6.0.3-8/zeppelin/conf/shiro.ini
	sed -i "/^#ldapRealm.userDnTemplate.*/s//ldapRealm.userDnTemplate = uid={0},CN=users,CN=accounts,DC=pochdp,DC=csi,DC=it/" /usr/hdp/2.6.0.3-8/zeppelin/conf/shiro.ini
	sed -i "/^JAVA_OPTS+.*/s//JAVA_OPTS+=\" -Dhttps.proxyHost=proxy-srv.csi.it -Dhttps.proxyPort=3128 -Dhttp.proxyHost=proxy-srv.csi.it -Dhttp.proxyPort=3128 -Dzeppelin.log.file=\${ZEPPELIN_LOGFILE}\"/" /usr/hdp/2.6.0.3-8/zeppelin/bin/zeppelin.sh
	echo "Checking alternatives"
	alternatives --list
	echo "Checking java"
	ls -lat /opt/jdk1.8.0_181/bin
	ls -lat /opt/jdk1.8.0_181/jre/bin
	java -version
	
	# Set proxy
	export http_proxy=$PROXY
	export https_proxy=$PROXY

	cd /usr/hdp/2.6.0.3-8/zeppelin	
	bin/zeppelin.sh
fi
	