#!/bin/bash

rm -rf /var/run/*.pid

# Kill Zeppelin process and remove .pid file
if [ -f /var/run/zeppelin/pid/zeppelin.pid ] ; then
	kill -9 $(cat /var/run/zeppelin/zeppelin.pid)
	echo "Zeppelin stopped"
	rm -f /var/run/zeppelin/pid//zeppelin.pid
fi

if [ -f /etc/ipa/ca.crt ] ; then
	echo "FreeIPA client is installed"
	echo "Starting the unenrollement"
	
	if [ -f /etc/hostname.ipa-client ] ; then
		HOSTNAME_IPA=$(cat /etc/hostname.ipa-client)
	else
		IPA=$( curl -si http://$IPASERVER/ | perl -lne 'm!^Location:\shttps?://(.+?)/! and print $1' )
		IPASERVERDOMAIN=${IPA#*.}
		HOSTNAME_IPA=$( hostname ).$IPASERVERDOMAIN
	fi
	
	ipa-join -h $HOSTNAME_IPA --unenroll
	rm -f /etc/krb5.keytab
	
	# Backup Zeppelin notebooks
	/usr/sbin/manage-notebooks.sh backup
else 
	echo "FreeIPA client is not installed."
fi
	